name: Generate Release on New Tag
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*.*.*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.4']
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zlib, mbstring
          
      - name: Install Composer Dependencies
        run: composer install -o -q --no-dev
        
      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "phpcs.xml" "composer.lock" ".gitignore" ".gitattributes" "tests/*" "phpunit.xml"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip
